version: "2"

run:
  go: "1.24"
  timeout: 5m

linters:
  default: all
  disable:
    - cyclop # We use maintidx to lint function complexity.
    - exhaustruct # This linter is meant to be used only for special cases. It is not recommended to use it for all files in a project.
    - funcorder
    - funlen
    - gocognit # We use maintidx to lint function complexity.
    - gocyclo # We use maintidx to lint function complexity.
    - interfacebloat # Warn when an interface has too many methods, not useful.
    - ireturn # Complain that interface A implementation method return an interface B... it's a requirement of interface A that is unavoidable.
    - mnd # Too picky. For example it says that 1000 (used in number of ms in one second) is a magic number.
    - noinlineerr # Why couldn't we inline errors ?
    - nonamedreturns # Warn for every named return, not useful.
    - varnamelen # I think there is too many false-positive.
    - wsl # Superseded by wsl_v5
  settings:
    depguard:
      rules:
        main:
          deny:
            - pkg: io/ioutil
              desc: ioutil is deprecated starting with Go 1.16
    gomoddirectives:
      replace-allow-list:
        - cloud.google.com/go
    nolintlint:
      require-specific: true
    revive:
      rules:
        - name: exported
          disabled: true
    tagliatelle:
      case:
        rules:
          json: snake
          yaml: snake
  exclusions:
    generated: lax
    presets:
      - common-false-positives
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
