version: 2
project_name: squirreldb-ingestor
snapshot:
  # Our version is based on the date.
  version_template: '{{ time "06.01.02.150405" }}'
before:
  hooks:
    - go mod download
    - go mod tidy
builds:
- env:
  - CGO_ENABLED=0
  targets:
  - linux_amd64
  - linux_386
  - linux_arm_6
  - linux_arm64
  - windows_amd64
  - windows_386
archives:
- format: binary
checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
release:
  # Don't try to modify Github
  disable: true
